version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "Gradle"
    assignees:
      - "aguirre-jes"
  - package-ecosystem: "docker"
    directory: "/src/main/docker"
    schedule:
      interval: "daily"
    labels:
      - "Docker"
    assignees:
      - "aguirre-jes"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "Github-actions"
    assignees:
      - "aguirre-jes"